name: "빌드 CI"

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - main
    paths:
      - "app/**"
      - "public/**"
      - "scripts/**"
      - "server/**"
      - "**/.config.ts"
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "public/**"
      - "scripts/**"
      - "server/**"
      - "**/.config.ts"
jobs:
  build:
    name: 빌드
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v4
        with:
          version: "9.5.0"
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        if: "github.event_name == 'push'"
        with:
          name: naedon-${{ github.sha }}
          path: .output/
          if-no-files-found: error
